name: deploy
on: 
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy package to digitalocean
        uses: appleboy/ssh-action@master
        with:
          host: "165.22.106.81"
          username: "root"
          password: "UZ65PrfzhHXfhaHZ"
          port: 22
          script: whoami
